### ISSUE TITLE
serial over USB?

### ISSUE THREAD

**Issue by ipsod** [MrYsLab/telemetrix-esp32#2]
Hi. 
I'd like to use serial over USB, instead of a wireless protocol, because I don't know enough about wireless transmission reliability and bandwidth saturation to know if I should trust it to run many connected ESP32 devices at once, particularly for my high-bandwidth application.  Is this something you'd be willing to add and/or support?  Also, might that go better in Telemetrix4Arduino, or would it go in this version?

**Comment by MrYsLab** [comment]
I am not planning on supporting a serial interface for the ESP32 because of the amount of testing involved. To implement this feature, the telemetrix-esp32 client and the [Telemetrix4Esp32](https://github.com/MrYsLab/Telemetrix4Esp32) server would need to be modified. The Telemetrix4Arduino API is not an exact match for the ESP32.

If you would like to tackle this on your own, on the server side, you could implement the serial interface similar to that for Telemetrix4Arduino. You would also need to substitute the client.write and the client to reads to serial equivalents.

You must decide how fancy you want things to be for the client. For example, you could build a simple interface where you specify the COM port manually or fully recreate the autoconnection scheme used for the Arduino.

I would be happy to provide guidance or answer any questions you might have. Creating a private fork would be low risk for you. I am not planning on adding any new features to the existing code.

**Comment by MrYsLab** [comment]
I will close this issue, but if you have any additional comments or questions, you may post them here, and I will see them.

**Comment by ipsod** [comment]
Ok, thank you.  I'll let you know if I have questions.
