### ISSUE TITLE
Please consider elaborating on explanations / including simple examples for beginners

### ISSUE THREAD

**Issue by chrisjdixon** [MrYsLab/telemetrix-esp32#4]
I'm trying to use telemetrix-esp32 and have no idea what's going on as I've never used ESP32 / Arduinos / Microprocessors / C++ before. I've tried to make sense of what to do from the users' guide but I can't find any examples on what code needs to run on the ESP32, or what networking settings we should configure. 

I was also confused by the client settings we should configure as I'm using PlatformIO in VS Code (already familiar with VS Code, trying to minimize new things to learn).

Could you please consider explaining what code should be included in the main.cpp / elsewhere on the ESP32, explaining what we might need to do for PlatformIO on VS Code, explaining how to configure networking / WiFi settings, or making these explanations more apparent? Or if this stuff is too basic for your intended users could you please consider directing beginners to a good explanation?

I'm only looking for the simplest possible way for a .py to tell an ESP32 to turn a relay on / off via WiFi. Any idea how I could find the simplest explanation possible? I feel like an idiot :sweat_smile: 

Thanks for any help!

**Comment by MrYsLab** [comment]
I am sorry that you are finding things so confusing. I will try to explain things, but if you need more explanation, please let me know, and I'll try to clarify.

First, I'd like to explain the high-level architecture of Telemetrix. Telemetrix consists of a client and a server. The server resides on the ESP32. It is a fixed program written in C++ that, once installed and configured, is intended not to need any additional programming or uploading to the ESP32. Its purpose is to listen for commands that arrive over a WIFI or Bluetooth transport. It interprets the command messages and acts upon them. For example, setting the mode of one of the ESP32 GPIO pins to be a digital input or perhaps a digital output. For pins commanded to be input pins, the server continuously polls the pin for any data changes and then automatically sends a report over the transport link.

The client is a Python program written using the [Telemetrix API.](https://htmlpreview.github.io/?https://github.com/MrYsLab/telemetrix-esp32/blob/master/html/telemetrix_esp32/index.html)

You may find the server installation instructions [here. ](https://mryslab.github.io/telemetrix-esp32/server/) You will need to [install the Arduino IDE](https://www.arduino.cc/en/software) to follow the instructions. You may be able to use PlatformIO, but that is beyond this project's scope.

On that page, you will also find instructions on modifying the server code to configure your router's SSID and password and how to retrieve the IP address assigned to the ESP32.

For the client API installation, please [follow this link.](https://mryslab.github.io/telemetrix-esp32/install_telemetrix/)

For your example of a relay, you could use the[ blink.py example ](https://github.com/MrYsLab/telemetrix-esp32/blob/master/examples/wifi/blink_wifi.py)to control a digital output pin.

If this has answered your questions, could you please close the issue? If not, please let me know what is still unclear.

Thanks.

**Comment by chrisjdixon** [comment]
Great, thank you very much!

> Telemetrix consists of a client and a server. The server resides on the ESP32. It is a fixed program written in C++ that, once installed and configured, is intended not to need any additional programming or uploading to the ESP32. Its purpose is to listen for commands that arrive over a WIFI or Bluetooth transport.

This cleared a lot up for me, thank you. Probably self evident for people familiar with micro controllers but maybe you could consider including this explanation for other dummies like me somewhere on [the intro page](https://mryslab.github.io/telemetrix-esp32/)?

I've followed instructions to the letter and have encountered this error:

> C:\Users\username\AppData\Local\Temp\.arduinoIDE-unsaved202408-22356-nbgzg0.hr63\Telemetrix4Esp32WIFI\Telemetrix4Esp32WIFI.ino:1697:11: error: 'LED_BUILTIN' was not declared in this scope

It seems [my ESP32](https://www.aliexpress.com/item/1005005564949759.html) doesn't have an `LED_BUILTIN`... [this thread](https://forum.arduino.cc/t/compilation-error-builtin-led-was-not-declared-in-this-scope/1073835) suggests that it's due to some boards not working with this function (symbol?). It seems I'll have to edit out `LED_BUILTIN` from your code but I've never coded with C++ before... any suggestions? 

Would you like me to now close this issue and for me to ask these dumb questions elsewhere? 

Thank you so much for the help!

**Comment by MrYsLab** [comment]
Firstly, your questions are not dumb and are very valid. 

When you have further questions, you may post to a closed issue, create a new one, or create a post in the discussions section. In all cases, I will receive notification of the posting.

I will undoubtedly consider expanding the intro section. Thanks for the suggestion.

For the compile error, I have created a new issue. This is issue MrYsLab/Telemetrix4Esp32#4. You can change the sketch if you'd like. To solve the issue, I will add an optional #define that needs to be set before compiling so that no reference to LED_BUILTIN will made and the compilation will succeed. I will also document this. It may take me a day or two to get to this. I will close issue MrYsLab/Telemetrix4Esp32#4 when it is available.

**Comment by MrYsLab** [comment]
@chrisjdixon Which ESP32 board are you using? I want to test the compilation against your board before publishing. Thanks.

**Comment by chrisjdixon** [comment]
[This is the ESP32 board I bought](https://www.aliexpress.com/item/1005005564949759.html), the "TYPE-C CH340C" variant. The chip has "ESP-32-WROOM" labelled on it, which I couldn't find among the esp32 libraries so I selected "ESP32 Dev Module" - is that alright? Someone has since helped me overcome the `LED_BUILTIN` issue by adding `#define LED_BUILTIN 2` to the top, although I doubt that'd suit as a universal fix.

Adapted your [blink.py](https://github.com/MrYsLab/telemetrix-esp32/blob/master/examples/wifi/blink_wifi.py) to blink the LED functionally to a regular .py, works perfectly, very impressive! Now that the LED is blinking I want to do other things such as power a pin to control a relay, but I don't know how. Is there a list of `board.` functions, such as `board.digital_write()` I could refer to?

Side note: I accidentally fried my board by trying to test whether `board.digital_write(16, 1)` worked with a multimeter, connecting alligator clamps to pin #16 and the GND pin. The alligator clamps may have touched other pins. Do you know why this might have happened, and what replacement board I should consider buying? 😅

**Comment by MrYsLab** [comment]
Thanks for providing the link for your board. I believe the board you should select in the Arduino IDE is the DOIT ESP32 DEVKIT V1.

![Screenshot from 2024-01-09 10-06-52](https://github.com/MrYsLab/telemetrix-esp32/assets/5189838/a83ac800-dbec-4229-9701-377b2fff152f)

This should support the LEDs, and you should not need to modify the code.
Please let me know if the LEDs work with this board version.

This was the only board available when I started working with the ESP32. There are now so many that it is hard to know which board library to pick. 

For the relay, here is [an article](https://randomnerdtutorials.com/esp32-relay-module-ac-web-server/) that should help explain things. Whatever relay board you pick, please ensure it includes a driver, preferably one with an opto-isolator. Connecting a relay coil directly to the ESP32 might destroy it because of the significant current drain on the output pin. 

Microcontroller boards are somewhat fragile, so please do not make any connections while the board is powered up and check your connections twice before applying power.

Another caution. The ESP32 is a 3-volt part. If you need to connect an input device that requires 5 volts to power it, such as the HC-SR04, please use a voltage divider or voltage converter to protect the ESP32. Also, I'd like to point out that the voltage on a digital output pin is 3v. If the device you need to drive requires 5V, the device may not work correctly. Here is an [article on voltage level shifters](https://randomnerdtutorials.com/how-to-level-shift-5v-to-3-3v/) that might be useful.

The board you are currently using should be OK. Unless you have a specific requirement that one of the other boards meet, there is no reason to change.

I will be making changes to the Arduino library to allow users with a board with no LED or one using the new ESP32-S3 devices to compile without error. Upgrading to this version should not be required if the LEDs work with the board selection mentioned above.

**Comment by MrYsLab** [comment]
I just published release 2.0.4 of Telemetrix4ESP32, which will allow the conditional compilation for the LED and ESP32 S3 processors. The Arduino folks should make it available for update in the IDE within the next day or so. Again, you don't need to update if the LEDs are working.

I also updated the user's guide with an introductory section. I also added documentation for implementing the above conditional compiles. The changes should be available within the next few hours.

I am closing this issue, but if you still have any problems or comments, please post them here, and I will see them.
